db:
    user: ENC[AES256_GCM,data:/myG+UOh+pRl94QM,iv:qPdrZQH0bwpTV6BZJDiOZM7fp5oXFfz6a2hxc+06OlI=,tag:8acsORXl+dGFp0xuiX8X7g==,type:str]
    password: ENC[AES256_GCM,data:MuMurncEY3hGguHwVtjrRJOVmNo=,iv:Hgj5JcKaOjER+cOu2m9LapNMS3QBUKF8HkzMcNeIzkQ=,tag:ooniHlZCTmaG4uq9lSpwIg==,type:str]
    host: ENC[AES256_GCM,data:6XgRIfm1UCfivpOexCjiXS95N8/jzxd4nFVB2E1HvyX/Bbf01HuG0di9bfsgS/UElS0=,iv:XAM+/FdERqRpZ1LdH/yEp2XjZlrnq13E/oZCmx4W+4w=,tag:nYxvowdpoi8YamB9D9V17A==,type:str]
    name: ENC[AES256_GCM,data:GdfmESR5Ukyq,iv:ncB72TUxXK6xJfNI7KGVH37h5riG7lln5HM5H1Mxrs8=,tag:Lh+pdkYKTz18WdloqQfggg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-05-07T09:02:38Z"
    mac: ENC[AES256_GCM,data:808y8ji8TSwlw3ec1NiC50xAxhsZa/hsoOfXjMeIBp2CRhbOuaM5g9R+vcAY+MAG4bm68Zg7Mipy7ZK62YVMri7XmHqP6JzU9KhkQrqSw4cvBULGn6ru8ax1EV4AOJdvQh8za7lIlD9ix0EVaBNzkh/ErvE4I2XlkTpNqUkEP7Q=,iv:b7zF2rfWQ9KCOlBIu574FVFPeSBsghH6kTbzKlYeUTk=,tag:ZjJ+vom7jYyXgiRS2D+pOA==,type:str]
    pgp:
        - created_at: "2024-05-07T09:02:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8KKJsxv30XFARAAnMDc99zwQDXTyxYfd7vmWKMJsNWiPDd5d31g1qVLicP+
            8zyGeTsY74aKN0bhK6iIaibcpFtW1/eZuFg1cV/Z3qjVYDm/O4BNbBhLaIeEdEmY
            QK/zjHLVB7XI2u8/JagEoTWgNblEpVfg5WibCjpPTOpNhZz46FI1yIZe5UBgsBi/
            esTbll81cL1rihRy47JdjWk9rjj+Q57aP4ukemgZLH/VZsemGFqaF6c+e54FfRnY
            suTtAyOCu3vwLs6h+PtuVtwPBdkuOsJK2NYm6IyNrpOq+VNA3vJfJYl5z3IdvhYO
            fbcl+nE4OgXzgQvncUzkI6mEAfRGrGj+yDnuKboxV8I4+ye1T6Yl0cAFvMz1v83k
            0AScYDfDBpNn7m3buebHUimXbZW3vmQFm2j98NBkfOs9cJXCuxpGsRpiH76ZTUh1
            nR9gxtRdUyJaJ8szsY5EMUbOww5hFchHLECmwJK9HfeN7HsnxRznqCLl9O8pptBa
            9EbwevyWwyCCyp2fT52JarlgxCKrzcFMIfl400m6E8a0kA8+IMA83nNbQl0fkM3L
            vrarWjMMooMliGhmZL0tyPMQCKk0eWeGUVtC90/daWvwh5V5DF5UCwAvCN0bdeAL
            nyE9vKLWqavtHpqP3a5hMgsS0FMfKz29jLl8Rp8I9clxCkpbzu5Z1iR6sUhUnLLS
            XAHFA+bpvyswZtIKPmgnusQ6LXJAR58Si9d4uFHCRqwmV24bygIiup9rEI57GWWZ
            e0pW0LQ9il6QjQiGEnLP92XcCpOP4MhfiLHFmhyte94bmRX6uxVhqUbzsPkA
            =XNEy
            -----END PGP MESSAGE-----
          fp: 5E61B3091634CF93EFA1739DE3F35712C7E9084D
    unencrypted_suffix: _unencrypted
    version: 3.8.1
