repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: v4.10.1
    namespace: ingress
    set:
      - name: controller.publishService.enabled
        value: true

# Apply CRDs beforehand!!!! kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.14.5/cert-manager.crds.yaml
  - name: cert-manager
    chart: jetstack/cert-manager
    version: v1.14.5
    namespace: cert-manager
