clusterName: "trialelkcluster"
replicas: 1 
minimumMasterNodes: 1 
createCert: true
secret:
  enabled: true
  password: ""
image: "docker.elastic.co/elasticsearch/elasticsearch"
imageTag: "8.5.1"
resources:
  requests:
    cpu: "200m"
    memory: "500Mi"
  limits:
    cpu: "300m"
    memory: "1Gi"
ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  hosts:
    - host: elastic.kinkinov.com
      paths:
        - path: /
  tls:
    - secretName: elastic-tls
      hosts:
        - elastic.kinkinov.com
