daemonset:

  extraEnvs:
    - name: "ELASTICSEARCH_HOSTS"
      value: "trialelkcluster-master:9200"
    - name: "ELASTICSEARCH_USERNAME"
      valueFrom:
        secretKeyRef:
          name: trialelkcluster-master-credentials
          key: username
    - name: "ELASTICSEARCH_PASSWORD"
      valueFrom:
        secretKeyRef:
          name: trialelkcluster-master-credentials
          key: password
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName

  filebeatConfig:
    filebeat.yml: |-
      filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"

      output.logstash:
        bulk_max_size: 20
        hosts: ['logstash-logstash.elk.svc.cluster.local:5044']
  
  secretMounts:
    - name: trialelkcluster-master-certs
      secretName: trialelkcluster-master-certs
      path: /usr/share/filebeat/certs/

  resources:
    limits:
      # Should avoid OOM (Error 137) when running goss tests into the pod
      memory: "300Mi"