daemonset:

  extraEnvs:
    - name: "ELASTICSEARCH_HOSTS"
      value: "elasticsearch-master:9200"
    - name: "ELASTICSEARCH_USERNAME"
      valueFrom:
        secretKeyRef:
          name: elasticsearch-master-credentials
          key: username
    - name: "ELASTICSEARCH_PASSWORD"
      valueFrom:
        secretKeyRef:
          name: elasticsearch-master-credentials
          key: password
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName

  filebeatConfig:
    filebeat.yml: |-
      logging.level: info
      logging.metrics.enabled: false
      logging.json: true
      filebeat.autodiscover:
        providers:
          - type: kubernetes
            node: ${NODE_NAME}
            hints.enabled: true
            hints.default_config.enabled: true
            hints.default_config:
              type: container
              paths:
                - /var/log/containers/*.log
              multiline.pattern: '^[^{]+'
              multiline.negate: false
              multiline.match: after
              processors:
                - add_kubernetes_metadata:
                    host: ${NODE_NAME}
                    matchers:
                    - logs_path:
                        logs_path: "/var/log/containers"
      filebeat.inputs:
        - type: filestream
          id: k8s-audit-logs
          paths:
            - /var/log/kube-apiserver-audit*
          parsers:
            - ndjson:
                keys_under_root: true

      processors:
        - decode_json_fields:
              fields: ["message"]
              process_array: false
              max_depth: 2
              target: ""
              overwrite_keys: true
              add_error_key: false

      output.logstash:
        bulk_max_size: 20
        hosts: ['logstash-logstash.elk.svc.cluster.local:5044']
  
  secretMounts:
    - name: elasticsearch-master-certs
      secretName: elasticsearch-master-certs
      path: /usr/share/filebeat/certs/

  resources:
    limits:
      # Should avoid OOM (Error 137) when running goss tests into the pod
      memory: "300Mi"