elasticsearchHosts: "https://trialelkcluster-master:9200"
elasticsearchCertificateSecret: trialelkcluster-master-certs
elasticsearchCredentialSecret: trialelkcluster-master-credentials
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  hosts:
    - host: kibana.kinkinov.com
      paths:
        - path: /
  tls:
    - secretName: kibana-tls
      hosts:
        - kibana.kinkinov.com
