elasticsearchHosts: "https://elasticsearch-master:9200"
elasticsearchCertificateSecret: elasticsearch-master-certs
elasticsearchCredentialSecret: elasticsearch-master-credentials
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  hosts:
    - host: monitoring.kinkinov.com
      paths:
        - path: /
  tls:
    - secretName: kibana-tls
      hosts:
        - monitoring.kinkinov.com
