apiVersion: v1
kind: PersistentVolume
metadata:
  name: sample-django-static-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClass: sample-django-static-nfs
  nfs:
    path: "/django"
    server: nfs.kinkinov.com
