apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sample-django.name" . }}-secrets
type: Opaque
stringData:
  DATABASE_URL: postgres://{{ .Values.db.user }}:{{ .Values.db.password }}@{{ .Values.db.host }}/{{ .Values.db.name }}